### ISSUE TITLE
handle errors rt bot

### ISSUE THREAD

**Issue by sibelius** [sibelius/ccsseraphini#714]
```jsx
{
  errors: [
    {
      title: 'operational-disconnect',
      disconnect_type: 'OperationalDisconnect',
      detail: 'This stream has been disconnected for operational reasons.',
      type: 'https://api.twitter.com/2/problems/operational-disconnect'
    }
  ]
}
```

**Comment by sibelius** [comment]
<img width="976" alt="image" src="https://user-images.githubusercontent.com/2005841/174502347-08cf8671-8cc1-4861-8004-cf7402aa0e5f.png">

**Comment by sibelius** [comment]
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/2005841/174696969-93059f6a-cc43-4728-b9b0-a974953eed92.png">

**Comment by sibelius** [comment]
<img width="982" alt="image" src="https://user-images.githubusercontent.com/2005841/175103767-c30bb735-5501-49f1-a259-de4cf3e31a49.png">

**Comment by sibelius** [comment]
TypeError: Cannot read properties of undefined (reading 'users')
2022-06-27T15:18:15.889848+00:00 app[worker.1]:     at processTweet (/app/build/bot.js:48836:33)
2022-06-27T15:18:15.889849+00:00 app[worker.1]:     at run (/app/build/bot.js:48845:11)
2022-06-27T15:18:15.889849+00:00 app[worker.1]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-06-27T15:18:15.889849+00:00 app[worker.1]:     at async /app/build/bot.js:48853:5
